name: CI
on:
  push:
    branches:
      - electron
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: electron
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: see directory in electron_dist
      run: ls
    - name: Install dependencies
      run: npm install
    - name: Build on MacOS
      env:
        ELECTRON: true
        APP_VERSION_NUMBER: 0.5.9
      run: npm run pack:mac
    - name: see directory
      run: ls
    - name: check env
      run: echo $ELECTRON $FEATHERS_URL
    - name: see directory in electron_dist
      run: ls ./bin
    - name: Upload output file
      uses: actions/upload-artifact@v1
      with:
        name: electron-mac
        path: ./bin/trtc-electron-simple-demo-0.1.0.dmg
  
  build_on_win:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@master
      with:
        ref: electron
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: install node tools
      run: npm install --global --production windows-build-tools@4.0.0
    - name: install node-gyp
      run: npm install --global node-gyp@latest
    - name: Set node config to use python2.7
      run: npm config set python python2.7
    - name: Set node config to set msvs_version to 2015
      run: npm config set msvs_version 2015
    - name: Install dependencies
      run: npm install
    - name: Build on Windows64
      env:
        ELECTRON: true
        APP_VERSION_NUMBER: 0.5.9
      run: npm run pack:win64
    - name: see directory 64
      run: ls ./bin
    - name: Upload output file 64
      uses: actions/upload-artifact@v1
      with:
        name: electron-win64
        path: ./bin/trtc-electron-simple-demo Setup 0.1.0.exe
    - name: Build on Windows32
      env:
        ELECTRON: true
        APP_VERSION_NUMBER: 0.5.9
      run: npm run pack:win32
    - name: see directory32
        run: ls ./bin
    - name: Upload output file
      uses: actions/upload-artifact@v1
      with:
        name: electron-win32
        path: ./bin/trtc-electron-simple-demo Setup 0.1.0.exe